### ISSUE TITLE
Custom fields in Time Tracking.

### ISSUE THREAD

**Issue by FlyLikeAPenguin** [Spring3/redshape#11]
Is it possible (or possible to add the ability) to enter custom field values in Redshape? We currently specify whether or not our time logs were for R&D using a custom field but I can't see that it's possible to do that in redshape?

**Comment by Spring3** [comment]
Hello @FlyLikeAPenguin . Thanks for your interest.

You are right, for now, it is not possible to set any custom fields to time entries.
I will try to find time to support this. But I can not give any estimations for now.

**Comment by rNoz** [comment]
Hi! We worked on this during the last week, but it is a custom solution, just as other features provided in our fork/PR, using server-side support.
This weekend we will provide those features. Of course, consider them "experimental". We supported around 5-7 types of custom fields, both in issues and time entries :). We will give more details soon.
