### ISSUE TITLE
Error - Certificate has expired

### ISSUE THREAD

**Issue by RolandSM** [Spring3/redshape#47]
Redshape cannot login: Error (certificate has expired)
But in Browser all is fine including a valid certificate?

Is there any Redshape Cache?

---
### Debug Info:
 ```
Redshape 1.1.0
Electron 8.0.1
linux 5.4.0-89-generic
Locale: de
```

**Comment by Spring3** [comment]
Hi @RolandSM.

The application doesn't have any caching layer.

**Comment by Spring3** [comment]
@RolandSM In my free time, I am working on an update to this app. Once it is ready, hopefully the issue will be resolved.

In the updated version, I plan to move the requests to the main thread, which I think will resolve any possible issues around CORS or certificates.

However, it will be a major rewrite, hence will take some time. Please stay tuned for the update and also thanks for the interest in this project. It remained unmaintained for a while, but I've recently gotten some time and motivation to refresh it.

**Comment by Spring3** [comment]
@RolandSM I've just experienced the same issue. The reason I got it was because I made a typo in the redmine endpoint on login page and it led to a website without an SSL certificate.

Please make sure you type the domain name correctly
